{% set name = "composio-client" %}
{% set version = "1.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/composio_client-{{ version }}.tar.gz
  sha256: 5df08f5a1db5973811a11b2778b0d9b3e8e919d60800e1069a39ce7e478ec138

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling ==1.26.3
    - hatch-fancy-pypi-readme
    - pip
  run:
    - python >={{ python_min }}
    - httpx >=0.23.0,<1
    - pydantic >=1.9.0,<3
    - typing_extensions >=4.10,<5
    - anyio >=3.5.0,<5
    - distro >=1.7.0,<2
    - sniffio

test:
  imports:
    - composio_client
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ComposioHQ/composio-base-py
  summary: The official Python library for the composio API
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
